version: 2
services:
  - type: web
    name: school-management-system
    runtime: python3
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 main:app"
    plan: free
    buildCommand: "pip install -r requirements.txt"
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12.0"
    autoDeploy: true
  
  - type: pserv
    name: school-db
    databaseName: school_management
    databaseUser: admin
    plan: free